export const INCREMENT_COUNTER2 = 'INCREMENT_COUNTER2';
export type INCREMENT_COUNTER2 = typeof INCREMENT_COUNTER2;

export const DECREMENT_COUNTER2 = 'DECREMENT_COUNTER2';
export type DECREMENT_COUNTER2 = typeof DECREMENT_COUNTER2;
