export const INCREMENT_COUNTER1 = 'INCREMENT_COUNTER1';
export type INCREMENT_COUNTER1 = typeof INCREMENT_COUNTER1;

export const DECREMENT_COUNTER1 = 'DECREMENT_COUNTER1';
export type DECREMENT_COUNTER1 = typeof DECREMENT_COUNTER1;
